module.exports = {
  token: process.env.TOKEN || "YOUR_BOT_TOKEN",
  prefix: process.env.PREFIX || "YOUR_BOT_PREFIX",
  embed: {
    color: "#2f3136",
    wrongcolor: "#2f3136",
    footertext: "Coded By Kabir Singh | Tech Boy Development",
    footericon:
      "https://images-ext-1.discordapp.net/external/C2xH2P5W4KM4F6wPxElhlzyVrZ5bjWl9_TPT-X_3hfs/%3Fsize%3D512/https/cdn.discordapp.com/avatars/894158815166095390/b3963f5de220e55d185c5b9d15648a82.webp?width=424&height=424",
  },
  emoji: {
    ERROR: "❌",
    SUCCESS: "✅",
    disabled: "🔴",
    enabled: "🟢",
    playing: "🎵",
    pruning: "📋",
    equalizer: "👀",
    cleared: "🧹",
    leave_on_empty: "🗣️",
    time: "⏲️",
    premium: "💰",
    song_by: "🗣️",
    dj: "🎧",
    search: "🔎",
    resume: "▶",
    pause: "⏸",
    lyrics: "📃",
    disk: "📀",
    ping: "🏓",
    rewind: "⏪",
    forward: "⏩",
    pause_resume: "⏯️",
    stop: "⏹️",
    previous_track: "⏮️",
    skip_track: "⏭️",
    replay_track: "🔃",
    reduce_volume: "🔉",
    raise_volume: "🔊",
    toggle_mute: "🔇",
    repeat_mode: "🔄",
    autoplay_mode: "♾",
    shuffle: "🔀",
    show_queue: "📑",
    show_current_track: "🩸",
    bot: "🤖",
  },
};
